# Generated by Django 5.1.4 on 2025-01-05 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="mealapp.recipe",
            ),
        ),
    ]
