# Generated by Django 5.1.4 on 2025-01-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealapp", "0002_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="calories_per_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="carbs_per_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fat_per_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="protein_per_unit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="aisle",
            field=models.IntegerField(default=0),
        ),
    ]
