# Generated by Django 5.1.4 on 2025-01-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mealapp", "0003_ingredient_calories_per_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="quantity",
            new_name="amount",
        ),
    ]
