# Generated by Django 4.0.6 on 2025-01-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0004_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='base_unit',
            field=models.CharField(default='unit', max_length=20),
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=20)),
                ('to_unit', models.CharField(max_length=20)),
                ('conversion_factor', models.FloatField()),
            ],
            options={
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
